/*
 * Copyright (C) 2016 donizyo
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.stellaris.ui;

import com.stellaris.Stellaris;
import com.stellaris.mod.ModLoader;
import com.stellaris.util.DigestStore;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.Reader;
import java.io.Writer;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author donizyo
 */
public class Main extends javax.swing.JFrame {

    private static final String TITLE_MAIN = "Stellaris IDE";
    private static final String FILE_MAIN_INI = "stellaris.ini";
    private static final String PROP_GAME = "stellaris.game";
    private static final String PROP_HOME = "stellaris.home";

    /**
     * Creates new form Main
     */
    public Main() {
        super(TITLE_MAIN);
        initComponents();
        WinUtils.mediateWindow(this);
    }

    private static boolean loadProperties() {
        Properties prop;
        String pathGame;
        String pathHome;
        WinPath winPath;
        String strPathHome;
        Stellaris st;

        prop = new Properties();
        try (Reader reader = new FileReader(
                new File(DigestStore.getUserDir(), FILE_MAIN_INI)
        );) {
            prop.load(reader);
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        pathGame = prop.getProperty(PROP_GAME);
        pathHome = prop.getProperty(PROP_HOME,
                ModLoader.getDefaultPathHome()
        );
        if (pathGame == null) {
            // launch file chooser
            winPath = new WinPath(pathGame, pathHome);
            winPath.setVisible(true);
            try {
                pathGame = winPath.getPathGame();
            } catch (InterruptedException ex) {
                pathGame = null;
            }
            try {
                strPathHome = winPath.getPathHome();
            } catch (InterruptedException ex) {
                strPathHome = null;
            }
            System.out.format("path.game=\"%s\"%npath.home=\"%s\"%n",
                    pathGame, pathHome);
            if (strPathHome != null) {
                pathHome = strPathHome;
            }
            try {
                storeProperties(pathGame, pathHome);
            } catch (IOException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if (pathGame == null) {
            // user didn't specify 'pathGame'
            // exit!
            return false;
        }
        st = new Stellaris();
        Stellaris.setDefault(st);
        st.init(pathGame);
        //st.scan(true);

        return true;
    }

    private static void storeProperties(String pathGame, String pathHome) throws IOException {
        Properties prop;

        prop = new Properties();
        if (pathGame != null) {
            prop.setProperty(PROP_GAME, pathGame);
        }
        if (pathHome != null) {
            prop.setProperty(PROP_HOME, pathHome);
        }
        try (Writer writer = new FileWriter(
                new File(DigestStore.getUserDir(), FILE_MAIN_INI)
        );) {
            prop.store(writer, "StellarisIDE UI");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        if (!loadProperties()) {
            return;
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
